services:
  mqtt:
    image: eclipse-mosquitto
    container_name: "mqtt"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
    ports:
      - "1883:1883"
      - "9001:9001"
  nodered:
    image: nodered/node-red
    container_name: "nodered"
    ports:
      - "1880:1880"
